### ISSUE TITLE
Wrong message regarding missing jars in 12.2

### ISSUE THREAD

**Issue by birbilis** [DelphiWorlds/Mosco#12]
At https://github.com/zoomicon/READCOM_App if I right click the FMX app project and set Mosco options to enable warning for jars
![image](https://github.com/user-attachments/assets/71debaaa-4ca2-4aeb-93c8-309f41c9f55d)

then build succeeds
![image](https://github.com/user-attachments/assets/6df3f2bb-5e29-46bd-b120-a2ba0873f82d)

but this warning is shown in Codex messages
![image](https://github.com/user-attachments/assets/8b72705f-47aa-477f-8a78-890890ba0540)

**Comment by DelphiWorlds** [comment]
This is not a Mosco issue - it's a Codex issue. I am also unable to reproduce the issue with Codex 2.4

**Comment by birbilis** [comment]
I'm on Delphi 12.2 and I've followed these instructions:
https://github.com/DelphiWorlds/HowTo/tree/main/Solutions/AndroidLowerVersions
to support minSdkVersion 21 (Android 5) instead of 23 that Delphi 12 has by default

so it might be related to that? I don't seem to have anyt issue building and I did build and upload to play store (https://play.google.com/store/apps/details?id=com.zoomicon.readcom.app&hl=el) without any problem using those settings

also, I know it is probably Codex issue, but that setting is at "Mosco options" dialog that Codex adds (so I wasn't sure where is more appropriate to post)

**Comment by DelphiWorlds** [comment]
> I'm on Delphi 12.2 and I've followed these instructions:

Those instructions do not have anything to do with the message you are seeing

The app at https://github.com/Zoomicon/READCOM_App/blob/master/App/READCOM_App.dproj is already configured for Delphi 12.2, which is why I do not see the message you are referring to. Is this the project you are opening when you see the message, or is it some other one?

**Comment by birbilis** [comment]
I see the message when building the project

however to be able to build it you need several steps:
https://github.com/Zoomicon/READCOM_App/wiki/Source-code

I'm also on Delphi 12.2 - I mentioned I changed some Android settings according to article I mentioned above to be able to lower the min Android SDK which Delphi 12 has set higher than it supports. Obviously I want to support as many devices as possible, so I opted to lower the min sdk target (which can't be done by just changing the number, need to change some paths at android settings in delphi sdk manager as mentioned in above article)

**Comment by DelphiWorlds** [comment]
> I see the message when building the project
> however to be able to build it you need several steps:

Then one of the steps is either changing READCOM_App.dproj, or another project is being loaded where the jars are not configured for Delphi 12.2, because that's what the Codex code does - when a project is loaded or changed, it checks the jars - this does not happen when the IDE is compiling a project unless the project changes in the process (which is unlikely)
